version: '3.9'

services:
  video-processor-service:
    build:
      context: ./VideoProcessingService
      dockerfile: Dockerfile
    deploy:
      replicas: 3 
    container_name: video-processing-service
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=VideoDB;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ASPNETCORE_URLS=http://*:7070
    networks:
      - backend
    ports:
      - "7071:7070"
    volumes:
      - video-zips:/app/zips

volumes:
  video-zips:
    name: my_shared_zips
    driver: local

networks:
  backend:
    external: true
