# Caminho: C:\Projetos\VideoProcessorX\docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: VideoProcessorX/VideoProcessorX/VideoProcessorX/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=VideoProcessingServiceDb;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - video-network
    volumes:
      - uploads:/app/uploads
      - zips:/app/zips
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: VideoProcessorX/VideoProcessorX/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=VideoProcessingServiceDb;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
    command: ["dotnet", "VideoProcessorX.dll", "--worker"]
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - video-network
    volumes:
      - uploads:/app/uploads
      - zips:/app/zips
    deploy:
      replicas: 4
    healthcheck:
      test: ["CMD", "pgrep", "dotnet"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - video-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit disk_free_limit 1GB"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - video-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  sql_data:
  uploads:
  zips:
  rabbitmq_data:

networks:
  video-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
