name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    name: 🛠️ Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do Código
        uses: actions/checkout@v3

      - name: 🔧 Configurar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: 📦 Restaurar Dependências
        run: dotnet restore VideoProcessingService/src/VideoProcessingService.Presentation/VideoProcessingService.Presentation.csproj

      - name: 🏗️ Build do Projeto
        run: dotnet build VideoProcessingService/src/VideoProcessingService.Presentation/VideoProcessingService.Presentation.csproj --no-restore --configuration Release

      - name: 🧪 Executar Testes Unitários
        run: dotnet test VideoProcessingService/src/VideoProcessingService.Presentation/VideoProcessingService.Presentation.csproj --no-build --configuration Release --logger trx
